MODEL:
  NUM_CLASSES: 81
  BACKBONE:
    NAME: 'efficient_net-b0'
    OUT_CHANNELS: (40, 112, 320, 256, 256, 256)
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("coco_2014_train",)
  TEST: ("coco_2014_val", )
SOLVER:
  MAX_ITER: 160000
  LR_STEPS: [105000, 135000]
  GAMMA: 0.1
  BATCH_SIZE: 2
  LR: 1e-3

OUTPUT_DIR: 'outputs/efficient_net_b3_ssd300_coco'
